// Packaged type effectiveness table.
//
// Values are multipliers in tenths (e.g. 20 => 2.0x, 5 => 0.5x, 0 => immune).

use std::collections::HashMap;

pub const TYPE_EFFECTS: &[(&str, &str, u8)] = &[
    ("BUG", "FIGHTING", 5),
    ("BUG", "FIRE", 5),
    ("BUG", "FLYING", 5),
    ("BUG", "GHOST", 5),
    ("BUG", "GRASS", 20),
    ("BUG", "POISON", 20),
    ("BUG", "PSYCHIC_TYPE", 20),
    ("DRAGON", "DRAGON", 20),
    ("ELECTRIC", "DRAGON", 5),
    ("ELECTRIC", "ELECTRIC", 5),
    ("ELECTRIC", "FLYING", 20),
    ("ELECTRIC", "GRASS", 5),
    ("ELECTRIC", "GROUND", 0),
    ("ELECTRIC", "WATER", 20),
    ("FIGHTING", "BUG", 5),
    ("FIGHTING", "FLYING", 5),
    ("FIGHTING", "GHOST", 0),
    ("FIGHTING", "ICE", 20),
    ("FIGHTING", "NORMAL", 20),
    ("FIGHTING", "POISON", 5),
    ("FIGHTING", "PSYCHIC_TYPE", 5),
    ("FIGHTING", "ROCK", 20),
    ("FIRE", "BUG", 20),
    ("FIRE", "DRAGON", 5),
    ("FIRE", "FIRE", 5),
    ("FIRE", "GRASS", 20),
    ("FIRE", "ICE", 20),
    ("FIRE", "ROCK", 5),
    ("FIRE", "WATER", 5),
    ("FLYING", "BUG", 20),
    ("FLYING", "ELECTRIC", 5),
    ("FLYING", "FIGHTING", 20),
    ("FLYING", "GRASS", 20),
    ("FLYING", "ROCK", 5),
    ("GHOST", "GHOST", 20),
    ("GHOST", "NORMAL", 0),
    ("GHOST", "PSYCHIC_TYPE", 0),
    ("GRASS", "BUG", 5),
    ("GRASS", "DRAGON", 5),
    ("GRASS", "FIRE", 5),
    ("GRASS", "FLYING", 5),
    ("GRASS", "GRASS", 5),
    ("GRASS", "GROUND", 20),
    ("GRASS", "POISON", 5),
    ("GRASS", "ROCK", 20),
    ("GRASS", "WATER", 20),
    ("GROUND", "BUG", 5),
    ("GROUND", "ELECTRIC", 20),
    ("GROUND", "FIRE", 20),
    ("GROUND", "FLYING", 0),
    ("GROUND", "GRASS", 5),
    ("GROUND", "POISON", 20),
    ("GROUND", "ROCK", 20),
    ("ICE", "DRAGON", 20),
    ("ICE", "FLYING", 20),
    ("ICE", "GRASS", 20),
    ("ICE", "GROUND", 20),
    ("ICE", "ICE", 5),
    ("ICE", "WATER", 5),
    ("NORMAL", "GHOST", 0),
    ("NORMAL", "ROCK", 5),
    ("POISON", "BUG", 20),
    ("POISON", "GHOST", 5),
    ("POISON", "GRASS", 20),
    ("POISON", "GROUND", 5),
    ("POISON", "POISON", 5),
    ("POISON", "ROCK", 5),
    ("PSYCHIC_TYPE", "FIGHTING", 20),
    ("PSYCHIC_TYPE", "POISON", 20),
    ("PSYCHIC_TYPE", "PSYCHIC_TYPE", 5),
    ("ROCK", "BUG", 20),
    ("ROCK", "FIGHTING", 5),
    ("ROCK", "FIRE", 20),
    ("ROCK", "FLYING", 20),
    ("ROCK", "GROUND", 5),
    ("ROCK", "ICE", 20),
    ("WATER", "DRAGON", 5),
    ("WATER", "FIRE", 20),
    ("WATER", "GRASS", 5),
    ("WATER", "GROUND", 20),
    ("WATER", "ROCK", 20),
    ("WATER", "WATER", 5),
];

pub fn type_chart() -> HashMap<String, HashMap<String, u8>> {
    let mut out: HashMap<String, HashMap<String, u8>> = HashMap::new();
    for (attacker, defender, factor) in TYPE_EFFECTS {
        out.entry((*attacker).to_string())
            .or_default()
            .insert((*defender).to_string(), *factor);
    }
    out
}
